// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-F1fuFYeqOwfWRENRygIkTw-0n6njmtY',
    appId: '1:476681175876:web:17a9418a8df213d2d58d11',
    messagingSenderId: '476681175876',
    projectId: 'mymusic-app-2025-d7025',
    authDomain: 'mymusic-app-2025-d7025.firebaseapp.com',
    storageBucket: 'mymusic-app-2025-d7025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5121jQpgL5jx7lVwrNkqYDess4lhM5o',
    appId: '1:476681175876:android:1264459be466d0b0d58d11',
    messagingSenderId: '476681175876',
    projectId: 'mymusic-app-2025-d7025',
    storageBucket: 'mymusic-app-2025-d7025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtI6njcJn4stySHQBH3yQYqQwqGD1gok',
    appId: '1:476681175876:ios:745531f1a8085002d58d11',
    messagingSenderId: '476681175876',
    projectId: 'mymusic-app-2025-d7025',
    storageBucket: 'mymusic-app-2025-d7025.firebasestorage.app',
    iosBundleId: 'com.example.mymusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtI6njcJn4stySHQBH3yQYqQwqGD1gok',
    appId: '1:476681175876:ios:745531f1a8085002d58d11',
    messagingSenderId: '476681175876',
    projectId: 'mymusic-app-2025-d7025',
    storageBucket: 'mymusic-app-2025-d7025.firebasestorage.app',
    iosBundleId: 'com.example.mymusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-F1fuFYeqOwfWRENRygIkTw-0n6njmtY',
    appId: '1:476681175876:web:31a3d91f2a4a4be6d58d11',
    messagingSenderId: '476681175876',
    projectId: 'mymusic-app-2025-d7025',
    authDomain: 'mymusic-app-2025-d7025.firebaseapp.com',
    storageBucket: 'mymusic-app-2025-d7025.firebasestorage.app',
  );
}
